SHOW_VIDEO=True
[INFO] loading model...
[INFO] starting process...
[INFO] starting video stream...
p_classifiers for cam:0 started
p_classifiers for cam:1 started

(python:24245): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(python:24245): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
p_classifiers for cam:2 started

(python:24245): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(python:24245): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
p_classifiers for cam:3 started
 * Running on http://0.0.0.0:3020/ (Press CTRL+C to quit)
198.166.220.49 - - [31/Oct/2020 05:04:37] "GET /urls?list=true HTTP/1.1" 200 -
[2020-10-31 05:04:54,039] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
[2020-10-31 05:04:54,039] ERROR in app: Exception on /moreimgs [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 296, in moreimgs
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
[2020-10-31 05:04:54,040] ERROR in app: Exception on /moreimgs [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 296, in moreimgs
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
[2020-10-31 05:04:54,040] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreparams?cam=0&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreparams?cam=1&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreimgs?start=0&cam=1&end=1&object_of_interest=car,person,cat,dog,truck,bus,train,motobike HTTP/1.1" 500 -
[2020-10-31 05:04:54,043] ERROR in app: Exception on /moreimgs [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 296, in moreimgs
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreimgs?start=0&cam=0&end=1&object_of_interest=car,person,cat,dog,truck,bus,train,motobike HTTP/1.1" 500 -
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreimgs?start=0&cam=2&end=1&object_of_interest=car,person,cat,dog,truck,bus,train,motobike HTTP/1.1" 500 -
[2020-10-31 05:04:54,043] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreparams?cam=2&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
[2020-10-31 05:04:54,073] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreparams?cam=3&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
[2020-10-31 05:04:54,076] ERROR in app: Exception on /moreimgs [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 296, in moreimgs
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:04:54] "GET /moreimgs?start=0&cam=3&end=1&object_of_interest=car,person,cat,dog,truck,bus,train,motobike HTTP/1.1" 500 -
[2020-10-31 05:05:05,140] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    conn = db.create_connection(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:05:05] "GET /moreparams?cam=0&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
198.166.220.49 - - [31/Oct/2020 05:05:05] "GET /favicon.ico HTTP/1.1" 404 -
[2020-10-31 05:14:55,149] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    db = Sql(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:14:55] "GET /moreparams?cam=0&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
[2020-10-31 05:14:55,874] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    db = Sql(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:14:55] "GET /moreparams?cam=1&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
[2020-10-31 05:14:55,876] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    db = Sql(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:14:55] "GET /moreparams?cam=2&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
[2020-10-31 05:14:55,878] ERROR in app: Exception on /moreparams [GET]
Traceback (most recent call last):
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/odroid/.virtualenvs/py3cv4/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "pi_object_detection.py", line 272, in moreparams
    params = gen_params(cam=cam, time1=hour_back1, time2=hour_back2 ,object_of_interest=object_of_interest)
  File "pi_object_detection.py", line 336, in gen_params
    db = Sql(DB_IP_ADDRESS)
AttributeError: module 'db.api' has no attribute 'create_connection'
198.166.220.49 - - [31/Oct/2020 05:14:55] "GET /moreparams?cam=3&hour_back1=0&hour_back2=1&object_of_interest=car HTTP/1.1" 500 -
